version: '1.0'
services:
  app1:
    image: sample-static-site-app1
    build: ./app1
    container_name: sample-static-site
    restart: always
    ports:
      - "8081:80"
  app2:
    image: sample-static-site-app2
    build: ./app2
    container_name: sample-static-site
    restart: always
    ports:
      - "8082:80"
  loadbalancer:
    build: ./nginx
    ports:
    - "80:80"
    depends_on:
    - app1
    - app2        
  db:
    image: percona:8
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    depends_on:
    - loadbalancer  
volumes:
  my-db: